site_name: Dehrang Dam Breach Analysis
site_url: https://007-wik.github.io/Dehrang-Dam-breach-Analysis_Panvel/
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
plugins:
  - search
nav:
  - Home: index.md
  - Full Report: report_content.md
  - Analysis Chapters:
      - 1. Storage Elevation Analysis: chapter1_storage_elevation.md
      - 2. DBA Basin HydroPrep: chapter2_basin_hydroprep.md
      - 3. DamBreak Analysis: chapter3_dambreak_analysis.md
      - 4. IDF Analysis Panvel: chapter4_idf_analysis.md
      - 5. Maps Generation (Colab): chapter5_maps_generation.md
  - Interactive Maps: maps.md