Run: Run_100Yr_Storm_IDF
     Default Description: Yes
     Log File: Run_100Yr_Storm_IDF.log
     DSS File: Run_100Yr_Storm_IDF.dss
     Is Save Spatial Results: Yes
     Spatial Results Write Interval: 60
     Last Modified Date: 18 April 2026
     Last Modified Time: 08:56:20
     Last Execution Date: 18 April 2026
     Last Execution Time: 08:56:10
     Basin: Basin 1
     Precip: 100Yr_Storm_IDF
     Control: Control IDF
     Save State Type: None
     Time-Series Output: Save All
     Time Series Results Manager Start:
     Time Series Results Manager End:
End:

Run: Run IMD_ABM_1DAY
     Default Description: Yes
     Log File: Run_IMD_ABM_1DAY.log
     DSS File: Run_IMD_ABM_1DAY.dss
     Is Save Spatial Results: Yes
     Spatial Results Write Interval: 60
     Last Modified Date: 18 April 2026
     Last Modified Time: 08:56:09
     Last Execution Date: 18 April 2026
     Last Execution Time: 08:56:05
     Basin: Basin 1
     Precip: IMD_ABM_1day
     Control: Control IDF
     Save State Type: None
     Time-Series Output: Save All
     Time Series Results Manager Start:
     Time Series Results Manager End:
End:

